### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ademilly** [ademilly/waterflow#2]
### General
- [ ] refactor flow
### Machine Learning Pipe
- [x] ML handling class
- [x] sklearn compatibility
- [ ] xgboost compatibility
- [ ] grid searching compatibility and such
- [ ] combining ML algos
